DROP TABLE IF EXISTS OLYMPICS_HISTORY;
CREATE TABLE IF NOT EXISTS OLYMPICS_HISTORY
(id INT, name VARCHAR(100), sex CHAR, age INT, height DECIMAL(10,2), weight DECIMAL(10,2), team VARCHAR(100), noc VARCHAR(50), 
games VARCHAR(100), year INT, season VARCHAR(50),city VARCHAR(100), sport VARCHAR(100),`event` VARCHAR(100), medal VARCHAR(50)
);

DROP TABLE IF EXISTS OLYMPICS_HISTORY_NOC_REGIONS;
CREATE TABLE IF NOT EXISTS OLYMPICS_HISTORY_NOC_REGIONS
(noc VARCHAR(50), region VARCHAR(100), notes VARCHAR(255));

select * from OLYMPICS_HISTORY;
select * from OLYMPICS_HISTORY_NOC_REGIONS;
